require:
  - rubocop-yard

plugins:
  - rubocop-md
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec
  - rubocop-thread_safety

AllCops:
  NewCops: enable
  SuggestExtensions: true
  TargetRubyVersion: 3.4

Metrics/MethodLength:
  CountAsOne:
    - array
    - hash
    - method_call

# Exclude our main gem include from the file naming convention, to keep it
# consistent with the gem name.
Naming/FileName:
  Exclude:
    - lib/cfa-security-controls-hyperproof.rb
    - README.md

RSpec/ExampleLength:
  CountAsOne:
    - array
    - hash
    - method_call

# Favor more reusable helpers.
RSpec/MultipleMemoizedHelpers:
  Max: 10
