# frozen_string_literal: true

source 'https://rubygems.org'

gemspec

group :development do
  gem 'rake', '~> 13.2'
  gem 'rubocop', '~> 1.75'
  gem 'rubocop-performance', '~> 1.25'
  gem 'rubocop-rake', '~> 0.7'
end
