name: Hyperproof Sync

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment to deploy to.
        default: production
        required: true
        type: environment

permissions:
  contents: read

jobs:
  collect:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-east-1
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          working-directory: ./hyperproof
      - name: Collect and sync proof
        working-directory: ./hyperproof
        run:
          bin/hyperproof collect
