name: Hyperproof Sync

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  collect:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          working-directory: ./hyperproof
      - name: Collect and sync proof
        working-directory: ./hyperproof
        run:
          bin/hyperproof collect
